# Generated by Django 6.1.1 on 2026-09-12 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_soal', models.TextField()),
                ('kunci_jawaban', models.TextField(help_text='Jawaban ideal untuk acuan AI.')),
                ('kriteria_penilaian', models.TextField(blank=True, help_text="Instruksi tambahan untuk AI (misal: 'Harus menyebutkan 3 pilar').", null=True)),
                ('skor_maksimal', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ujian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('waktu_mulai', models.DateTimeField()),
                ('waktu_selesai', models.DateTimeField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JawabanSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_jawaban', models.TextField()),
                ('waktu_kumpul', models.DateTimeField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban', to=settings.AUTH_USER_MODEL)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_siswa', to='lms_app.soal')),
            ],
            options={
                'unique_together': {('soal', 'siswa')},
            },
        ),
        migrations.CreateModel(
            name='PenilaianAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor_ai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback_ai', models.TextField(blank=True, help_text='Alasan AI memberikan skor tersebut', null=True)),
                ('skor_akhir_instruktur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Antrean'), ('PROCESSING', 'Sedang Diproses AI'), ('COMPLETED', 'Selesai'), ('FAILED', 'Gagal')], default='PENDING', max_length=20)),
                ('diproses_pada', models.DateTimeField(blank=True, null=True)),
                ('jawaban', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian', to='lms_app.jawabansiswa')),
            ],
        ),
        migrations.AddField(
            model_name='soal',
            name='ujian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_soal', to='lms_app.ujian'),
        ),
    ]
