# Generated by Django 6.1.1 on 2026-09-13 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Kursus',
            },
        ),
        migrations.AddField(
            model_name='ujian',
            name='kursus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daftar_ujian', to='lms_app.kursus'),
        ),
        migrations.CreateModel(
            name='Enrollmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_enroll', models.DateTimeField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollmen', to=settings.AUTH_USER_MODEL)),
                ('kursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_enrollmen', to='lms_app.kursus')),
            ],
            options={
                'unique_together': {('kursus', 'siswa')},
            },
        ),
    ]
