# Generated by Django 6.1.1 on 2026-09-13 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_kursus_ujian_kursus_enrollmen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_penugasan', models.DateTimeField(auto_now_add=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajaran', to=settings.AUTH_USER_MODEL)),
                ('kursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_pengajaran', to='lms_app.kursus')),
            ],
            options={
                'unique_together': {('kursus', 'guru')},
            },
        ),
    ]
